### ISSUE TITLE
Rename...

### ISSUE THREAD

**Issue by jamtur01** [kountable/ssmsh#6]
Awesome tool - thank you - a lot of folks are likely to be confused by the `ssh` in the name perhaps? c.f. https://www.google.com/search?q=pssh. ssmsh might work better perhaps?

**Comment by bwhaley** [comment]
It's a good suggestion, and not the first time I've heard it. It's well known of course that naming is one of the hardest things in computer science... :) I'll implement your suggestion! Thanks.
