### ISSUE TITLE
Please add compile instructions

### ISSUE THREAD

**Issue by awsandrewpark** [kountable/ssmsh#9]
As per the subject line, it'd be nice if you added a section on how to compile the product (which should be platform specifc).

**Comment by bwhaley** [comment]
I can add some details, but basically just clone the repo and run `make` or `go build`!

**Comment by awsandrewpark** [comment]
Hi,

Thanks for the response.

You are right, it IS as easy as "go build" but I had to fulfill some dependencies... namely,
git clone git@github.com:abiosoft/ishell.git ~/go/src/github.com/abisoft/ishell
git clone git@github.com:chzyer/readline.git ~/go/src/github.com/chzyer/readline
git clone git@github.com:fatih/color.git ~/go/src/github.com/fatih/color
git clone git@github.com:flynn-archive/go-shlex.git ~/go/src/github.com/flynn-archive/go-shlex
git clone git@github.com:kountable/ssmsh.git ~/go/src/github.com/kountable/ssmsh
git clone git@github.com:mattn/go-shellwords.git ~/go/src/github.com/mattn/go-shellwords

I tried the make command as well.  This needed more directory structure configuration and even after that, I am getting an error:
../../go/src/_/Users/anonymous/Downloads/ssmsh/commands/put.go:57:12: cannot assign *"github.com/kountable/ssmsh/vendor/github.com/aws/aws-sdk-go/service/ssm".PutParameterOutput to resp (type *"_/Users/anonymous/Downloads/ssmsh/vendor/github.com/aws/aws-sdk-go/service/ssm".PutParameterOutput) in multiple assignment
../../go/src/_/Users/anonymous/Downloads/ssmsh/commands/put.go:57:21: cannot use &putParamInput (type *"_/Users/anonymous/Downloads/ssmsh/vendor/github.com/aws/aws-sdk-go/service/ssm".PutParameterInput) as type *"github.com/kountable/ssmsh/vendor/github.com/aws/aws-sdk-go/service/ssm".PutParameterInput in argument to ps.Put
make: *** [_/Users/anonymous/Downloads/ssmsh/commands] Error 2

All I am pointing out here is that, this is an excellent tool and I suspect that it will gain some interest from many people.  If some of the "requirements" and how to go about resolving those requirements are captured in an installation document, it'll save many people many hours.  Especially for those people who are not familiar with golang (myself included).

Anyways, mine compiled using "go build" so I'm going to continue to use that.  If you wish, I can help with the documentation and perhaps even with the feature enhancements (I will have to use this as a Golang learning experience though).

**Comment by bwhaley** [comment]
Thanks for the additional info! I haven't done a "fresh" clone of the repo and attempted a build in a while. I'll try to go through some of this pain myself, fix any issues, then document the process in the README.

**Comment by bwhaley** [comment]
Hey there, I added a section on compiling, tested with a fresh ubuntu Xenial VM. Thanks for your feedback and let me know if you have any problems with it.
